shared:
  rpc_host: your_node_address_here
  rpc_path: /path_to_prepend_to_rpc_urls

test:
  database:
    name: bakerhub_indexer_test

development: {}

staging:
  secret_key_base: <SECRET_KEY_BASE>
  database:
    name: bakerhub_indexer_staging
    user: postgres
    password: <DB PASSWORD>
    host: <DB URL>

production:
  secret_key_base: <SECRET_KEY_BASE>
  database:
    name: bakerhub_indexer
    user: bakerhub
    password: <DB PASSWORD>
    host: <DB URL>
