default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch('BAKERHUB_INDEXER_DATABASE_NAME') { Rails.application.credentials.dig(Rails.env.to_sym, :database, :name) || 'bakerhub_indexer_dev' } %>
  host: <%= ENV.fetch('BAKERHUB_INDEXER_DATABASE_HOST') { Rails.application.credentials.dig(Rails.env.to_sym, :database, :host) || 'localhost' } %>
  user: <%= ENV.fetch('BAKERHUB_INDEXER_DATABASE_USER') { Rails.application.credentials.dig(Rails.env.to_sym, :database, :user) } %>
  password: <%= ENV.fetch('BAKERHUB_INDEXER_DATABASE_PASSWORD') { Rails.application.credentials.dig(Rails.env.to_sym, :database, :password) } %>
  port: <%= ENV.fetch('BAKERHUB_INDEXER_DATABASE_PORT') { Rails.application.credentials.dig(Rails.env.to_sym, :database, :port) } %>

development:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
test:
  <<: *default
